/* Generates lib/checks.js from 06_app/index.html.
 *
 * index.html stays the single source of truth for the reference tables and
 * the analysis logic (the app is deliberately one self-contained file). The
 * WhatsApp bot runs the same checks server-side, so instead of hand-copying
 * 129 rows and ~60 lines of logic — which is exactly how this project's
 * reference data drifted before — this script slices the exact source text
 * out of index.html and wraps it as a Node module.
 *
 *   node lib/build_checks.js          rewrite lib/checks.js
 *   node lib/build_checks.js --check  exit 1 if lib/checks.js is stale
 */
const fs = require('fs');
const path = require('path');

const HTML = path.join(__dirname, '..', 'index.html');
const OUT = path.join(__dirname, 'checks.js');

function between(src, startMarker, endMarker) {
  const s = src.indexOf(startMarker);
  if (s < 0) throw new Error('start marker not found: ' + startMarker);
  const e = src.indexOf(endMarker, s);
  if (e < 0) throw new Error('end marker not found: ' + endMarker);
  return src.slice(s, e);
}

function build() {
  const src = fs.readFileSync(HTML, 'utf8').replace(/\r\n/g, '\n');
  const parts = [
    // NON_PAYABLE + NPPA (+ their comments)
    between(src, 'const NON_PAYABLE = [', '// Full IS 19493:2025 header registry'),
    // IS19493_HEADER + GSTIN_RE
    between(src, '// Full IS 19493:2025 header registry', '// The real, redacted 6-page bill'),
    // money()
    between(src, 'const money = n =>', '\nconst $ = id'),
    // bestMatch() + analyse()
    between(src, '/* checks */', 'function sectionSums(lines){'),
  ];
  return (
    '/* AUTO-GENERATED by lib/build_checks.js from 06_app/index.html — do not edit.\n' +
    ' * Re-run `node lib/build_checks.js` after changing the reference tables or\n' +
    ' * analyse() in index.html. `node lib/build_checks.js --check` fails if stale. */\n' +
    parts.join('\n') + '\n' +
    'module.exports = { NON_PAYABLE, NPPA, IS19493_HEADER, GSTIN_RE, money, bestMatch, parseAmount, analyse };\n'
  );
}

if (require.main === module) {
  const out = build();
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : '';
    if (cur !== out) { console.error('lib/checks.js is STALE — run: node lib/build_checks.js'); process.exit(1); }
    console.log('lib/checks.js is in sync with index.html');
  } else {
    fs.writeFileSync(OUT, out);
    console.log('wrote lib/checks.js (' + out.length + ' chars)');
  }
}
module.exports = { build };
