/* Generates lib/checks.js from 06_app/index.html.
 *
 * index.html stays the single source of truth for the reference tables and
 * the analysis logic (the app is deliberately one self-contained file). The
 * release gate (lib/run_gates.js) runs the same checks in Node, so instead of hand-copying
 * 129 rows and ~60 lines of logic — which is exactly how this project's
 * reference data drifted before — this script slices the exact source text
 * out of index.html and wraps it as a Node module.
 *
 *   node lib/build_checks.js          rewrite lib/checks.js
 *   node lib/build_checks.js --check  exit 1 if lib/checks.js is stale
 */
const fs = require('fs');
const path = require('path');

const HTML = path.join(__dirname, '..', 'index.html');
const OUT = path.join(__dirname, 'checks.js');

function between(src, startMarker, endMarker) {
  const s = src.indexOf(startMarker);
  if (s < 0) throw new Error('start marker not found: ' + startMarker);
  const e = src.indexOf(endMarker, s);
  if (e < 0) throw new Error('end marker not found: ' + endMarker);
  return src.slice(s, e);
}

function build() {
  const src = fs.readFileSync(HTML, 'utf8').replace(/\r\n/g, '\n');
  const parts = [
    // NON_PAYABLE + NPPA (+ their comments)
    between(src, 'const NON_PAYABLE = [', '// Full IS 19493:2025 header registry'),
    // IS19493_HEADER + GSTIN_RE
    between(src, '// Full IS 19493:2025 header registry', '// The real, redacted 6-page bill'),
    // money()
    between(src, 'const money = n =>', '\nconst $ = id'),
    // bestMatch() + analyse()
    between(src, '/* checks */', 'function sectionSums(lines){'),
  ];
  return (
    '/* AUTO-GENERATED by lib/build_checks.js from 06_app/index.html — do not edit.\n' +
    ' * Re-run `node lib/build_checks.js` after changing the reference tables or\n' +
    ' * analyse() in index.html. `node lib/build_checks.js --check` fails if stale. */\n' +
    parts.join('\n') + '\n' +
    'module.exports = { NON_PAYABLE, NPPA, IS19493_HEADER, GSTIN_RE, money, bestMatch, parseAmount, analyse };\n'
  );
}

// The photo-reading logic (between the "reader" markers in index.html) is copied
// into lib/reader.js so it can be tested in Node with a mock fetch. It must be
// DOM-free: if someone adds a page reference the build fails, instead of a test
// silently passing against a stub.
const OUT_READER = path.join(__dirname, 'reader.js');
function buildReader() {
  const src = fs.readFileSync(HTML, 'utf8').replace(/\r\n/g, '\n');
  const region = between(src, '/* reader */', '/* /reader */');
  const banned = region.match(/\b(document|window|localStorage|sessionStorage|navigator|statusEl)\b|\$\(|\bS\(\)/);
  if (banned) throw new Error('reader region references the page (' + banned[0] + ') - it must stay DOM-free');
  return (
    '/* AUTO-GENERATED by lib/build_checks.js from the "reader" region of 06_app/index.html - do not edit.\n' +
    ' * Re-run `node lib/build_checks.js` after changing that region. `--check` fails if stale. */\n' +
    region + '\n' +
    'module.exports = { PHOTO_MIME, fileMime, isPhoto, fileKey, mkErr, kindForStatus, readOnePage, readPages };\n'
  );
}

if (require.main === module) {
  const out = build(), outReader = buildReader();
  if (process.argv.includes('--check')) {
    const norm = f => fs.existsSync(f) ? fs.readFileSync(f, 'utf8').replace(/\r\n/g, '\n') : '';
    if (norm(OUT) !== out) { console.error('lib/checks.js is STALE — run: node lib/build_checks.js'); process.exit(1); }
    if (norm(OUT_READER) !== outReader) { console.error('lib/reader.js is STALE — run: node lib/build_checks.js'); process.exit(1); }
    console.log('lib/checks.js and lib/reader.js are in sync with index.html');
  } else {
    fs.writeFileSync(OUT, out);
    fs.writeFileSync(OUT_READER, outReader);
    console.log('wrote lib/checks.js (' + out.length + ' chars) and lib/reader.js (' + outReader.length + ' chars)');
  }
}
module.exports = { build, buildReader };
