/* AUTO-GENERATED by lib/build_checks.js from 06_app/index.html — do not edit.
 * Re-run `node lib/build_checks.js` after changing the reference tables or
 * analyse() in index.html. `node lib/build_checks.js --check` fails if stale. */
const NON_PAYABLE = [
  { tier:"exact", item:"Admission/Registration Charges", keywords:"admission service|registration charge|admission charge" },
  { tier:"exact", item:"Medical Records", keywords:"medical record" },
  { tier:"exact", item:"Documentation Charges / Administrative Expenses", keywords:"documentation charge|administrative expense|admin charge" },
  { tier:"exact", item:"TPA Charges", keywords:"tpa charge|insurance processing|insurance charge" },
  { tier:"exact", item:"Discharge Procedure Charges", keywords:"discharge procedure|discharge charge" },
  { tier:"exact", item:"Certificate Charges", keywords:"certificate charge" },
  { tier:"exact", item:"Medical Certificate", keywords:"medical certificate" },
  { tier:"exact", item:"Birth Certificate", keywords:"birth certificate" },
  { tier:"exact", item:"Photocopies Charges", keywords:"photocopy|photocopies|xerox" },
  { tier:"exact", item:"Courier Charges", keywords:"courier" },
  { tier:"exact", item:"Conveyance Charges", keywords:"conveyance" },
  { tier:"exact", item:"Medico Legal Case Charges", keywords:"medico legal|mlc charge" },
  { tier:"exact", item:"Maintenance Charges", keywords:"maintenance charge" },
  { tier:"exact", item:"Surcharges", keywords:"surcharge" },
  { tier:"exact", item:"Attendant Charges", keywords:"attendant charge" },
  { tier:"exact", item:"Entrance Pass / Visitors Pass Charges", keywords:"visitor pass|entrance pass" },
  { tier:"exact", item:"Incidental Expenses / Misc. Charges", keywords:"incidental|miscellaneous charge|misc charge" },
  { tier:"exact", item:"Daily Chart Charges", keywords:"daily chart" },
  { tier:"exact", item:"Diabetic Chart Charges", keywords:"diabetic chart" },
  { tier:"exact", item:"Preparation Charges", keywords:"preparation charge" },
  { tier:"exact", item:"Patient Identification Band / Name Tag", keywords:"identification band|name tag|id band" },
  { tier:"exact", item:"Blood Reservation Charges / Ante Natal Booking", keywords:"blood reservation|ante natal booking" },
  { tier:"review", item:"Service Charges Where Nursing Charge Also Charged", keywords:"service charge" },
  { tier:"review", item:"Referral Doctor's Fees", keywords:"referral doctor|referral fee" },
  { tier:"exact", item:"Alcohol Swabs", keywords:"alco swab|alcohol swab|alcohol gauze" },
  { tier:"exact", item:"Scrub Solution / Sterillium", keywords:"sterillium|scrub solution|propanol|alcorub|povidone scrub|hand rub" },
  { tier:"exact", item:"Savlon", keywords:"savlon" },
  { tier:"exact", item:"Hand Wash", keywords:"hand wash" },
  { tier:"review", item:"Micro Shield", keywords:"micro shield|microshield" },
  { tier:"exact", item:"Washing Charges", keywords:"washing charge" },
  { tier:"exact", item:"Laundry Charges", keywords:"laundry" },
  { tier:"review", item:"Clean Sheet", keywords:"clean sheet" },
  { tier:"exact", item:"Examination Gloves", keywords:"gloves examination|examination glove|exam glove|nitrile glove|glove nitrile|examination medium nitrile" },
  { tier:"review", item:"Surgical Gloves (sterile, in-procedure)", keywords:"surgical glove|glove size|gammex|encore" },
  { tier:"exact", item:"Paper Gloves", keywords:"paper glove" },
  { tier:"exact", item:"Mask", keywords:"face mask|flexi mask|surgical mask" },
  { tier:"exact", item:"Apron", keywords:"apron" },
  { tier:"exact", item:"Gown", keywords:"gown" },
  { tier:"exact", item:"Shoe Cover", keywords:"shoe cover|foot cover" },
  { tier:"exact", item:"Caps", keywords:"surgical cap|theatre cap" },
  { tier:"exact", item:"Camera Cover", keywords:"camera cover" },
  { tier:"exact", item:"Trolly Cover", keywords:"trolley cover|trolly cover" },
  { tier:"exact", item:"Carry Bags", keywords:"carry bag" },
  { tier:"exact", item:"Band Aids, Bandages, Sterile Injections, Needles, Syringes", keywords:"band aid|bandaid" },
  { tier:"review", item:"Cotton", keywords:"cotton roll|absorbent cotton" },
  { tier:"exact", item:"Cotton Bandage", keywords:"cotton bandage" },
  { tier:"exact", item:"Crepe Bandage", keywords:"crepe bandage" },
  { tier:"exact", item:"Hansaplast / Adhesive Bandages", keywords:"hansaplast|adhesive bandage" },
  { tier:"review", item:"Gauze", keywords:"gauze|gauge soft" },
  { tier:"review", item:"Cliniplast", keywords:"cliniplast" },
  { tier:"review", item:"Curapore", keywords:"curapore" },
  { tier:"review", item:"Blade", keywords:"blade" },
  { tier:"review", item:"Tourniquet", keywords:"tourniquet" },
  { tier:"exact", item:"Eyelet Collar", keywords:"eyelet collar" },
  { tier:"review", item:"Eye Pad", keywords:"eye pad" },
  { tier:"review", item:"Eye Shield", keywords:"eye shield" },
  { tier:"review", item:"Bed Pan", keywords:"bed pan|bedpan" },
  { tier:"exact", item:"Bed Under Pad Charges", keywords:"under pad|underpad" },
  { tier:"exact", item:"Diaper of Any Type", keywords:"diaper" },
  { tier:"review", item:"Blanket / Warmer Blanket", keywords:"blanket" },
  { tier:"exact", item:"Admission Kit", keywords:"admission kit" },
  { tier:"exact", item:"Kidney Tray", keywords:"kidney tray" },
  { tier:"exact", item:"Ounce Glass", keywords:"ounce glass" },
  { tier:"exact", item:"Urine Container", keywords:"urine container" },
  { tier:"exact", item:"Urometer, Urine Jug", keywords:"urometer|urine jug" },
  { tier:"review", item:"Medicine Box", keywords:"medicine box" },
  { tier:"exact", item:"Thermometer", keywords:"thermometer" },
  { tier:"exact", item:"Comb", keywords:"comb" },
  { tier:"exact", item:"Brush", keywords:"tooth brush|toothbrush" },
  { tier:"exact", item:"Tooth Paste", keywords:"tooth paste|toothpaste" },
  { tier:"exact", item:"Towel", keywords:"towel|cosy towel" },
  { tier:"exact", item:"Slippers", keywords:"slipper" },
  { tier:"exact", item:"Sanitary Pad", keywords:"sanitary pad" },
  { tier:"exact", item:"Tissue Paper", keywords:"tissue paper" },
  { tier:"exact", item:"Powder", keywords:"talcum powder" },
  { tier:"exact", item:"Moisturiser / Paste / Brush", keywords:"moisturiser|moisturizer" },
  { tier:"exact", item:"Eau-De-Cologne / Room Freshners", keywords:"room freshener|room freshner|cologne" },
  { tier:"exact", item:"Mineral Water", keywords:"mineral water" },
  { tier:"exact", item:"Buds", keywords:"ear bud|cotton bud|buds" },
  { tier:"exact", item:"Barber Charges", keywords:"barber" },
  { tier:"exact", item:"Beauty Services", keywords:"beauty service" },
  { tier:"exact", item:"Baby Charges", keywords:"baby charge" },
  { tier:"exact", item:"Baby Food", keywords:"baby food|lactogen|infant food" },
  { tier:"exact", item:"Baby Utilities Charges", keywords:"baby utilities" },
  { tier:"exact", item:"Baby Set", keywords:"baby set" },
  { tier:"exact", item:"Baby Bottles", keywords:"baby bottle|feeding bottle" },
  { tier:"exact", item:"Cradle Charges", keywords:"cradle" },
  { tier:"exact", item:"Vaccine Charges for Baby", keywords:"baby vaccine|vaccine charges for baby" },
  { tier:"exact", item:"Telephone Charges", keywords:"telephone charge" },
  { tier:"exact", item:"Email / Internet Charges", keywords:"internet charge|email charge|wifi" },
  { tier:"exact", item:"DVD, CD Charges", keywords:"dvd charge|cd charge" },
  { tier:"exact", item:"Guest Services", keywords:"guest service" },
  { tier:"exact", item:"Food Charges (Other than Patient's Diet)", keywords:"attendant food|guest food|visitor food" },
  { tier:"exact", item:"Walking Aids Charges", keywords:"walking aid|walker charge" },
  { tier:"review", item:"BiPAP Machine", keywords:"bipap" },
  { tier:"review", item:"Commode", keywords:"commode" },
  { tier:"review", item:"Oxygen Cylinder (usage outside hospital)", keywords:"oxygen cylinder" },
  { tier:"exact", item:"Oxygen Mask", keywords:"oxygen mask" },
  { tier:"exact", item:"Spacer", keywords:"spacer", not:"cage|interbody|cement|knee|hip|spine|spinal|vertebral|antibiotic|implant" },
  { tier:"review", item:"SPO2 Probe", keywords:"spo2 probe|spo2 sensor" },
  { tier:"exact", item:"Nebulizer Kit", keywords:"nebulizer kit|nebuliser kit|nebulisation kit|nebulization kit" },
  { tier:"exact", item:"Steam Inhaler", keywords:"steam inhaler" },
  { tier:"exact", item:"Arm Sling", keywords:"arm sling|armsling" },
  { tier:"exact", item:"Cervical Collar", keywords:"cervical collar" },
  { tier:"exact", item:"Ambulance Collar", keywords:"ambulance collar" },
  { tier:"exact", item:"Ambulance Equipment", keywords:"ambulance equipment" },
  { tier:"exact", item:"Splint", keywords:"splint" },
  { tier:"exact", item:"Knee Braces", keywords:"knee brace" },
  { tier:"exact", item:"Knee/Shoulder Immobilizer", keywords:"immobilizer|immobiliser" },
  { tier:"exact", item:"Diabetic Foot Wear", keywords:"diabetic footwear|diabetic foot wear" },
  { tier:"exact", item:"Visco Belt Charges", keywords:"visco belt" },
  { tier:"exact", item:"Cold Pack / Hot Pack", keywords:"cold pack|hot pack" },
  { tier:"review", item:"Hand Holder", keywords:"hand holder" },
  { tier:"review", item:"Any Kit With No Details Mentioned", keywords:"kit" },
  { tier:"review", item:"CSSD / Sterilisation Charges", keywords:"cssd|sterilisation charge|sterilization charge" },
  { tier:"review", item:"ECG Electrodes / Leads", keywords:"ecg lead|ecg electrode" },
  { tier:"review", item:"Dressing / Tegaderm film", keywords:"tegaderm|transparent dressing" },
  { tier:"exact", item:"Weight Control Programs / Supplies / Services", keywords:"weight control|obesity program" },
  { tier:"exact", item:"Spectacles / Contact Lenses / Hearing Aids", keywords:"spectacle|contact lens|hearing aid" },
  { tier:"exact", item:"Dental Treatment Not Requiring Hospitalisation", keywords:"dental treatment", basis:"policy_exclusion" },
  { tier:"exact", item:"Hormone Replacement Therapy", keywords:"hormone replacement", basis:"policy_exclusion" },
  { tier:"exact", item:"Home Visit Charges", keywords:"home visit" },
  { tier:"exact", item:"Infertility / Assisted Conception", keywords:"infertility|assisted conception|ivf treatment|ivf cycle|ivf procedure|in vitro fertilisation|in vitro fertilization", basis:"policy_exclusion" },
  { tier:"exact", item:"Obesity Treatment", keywords:"bariatric|obesity treatment", basis:"policy_exclusion" },
  { tier:"exact", item:"Corrective Surgery for Refractive Error", keywords:"lasik|refractive error", basis:"policy_exclusion" },
  { tier:"exact", item:"Donor Screening Charges", keywords:"donor screening" },
  { tier:"exact", item:"Hospitalisation for Evaluation / Diagnostic Purpose", keywords:"evaluation only|diagnostic admission" },
  { tier:"exact", item:"Aesthetic Treatment / Surgery", keywords:"aesthetic|cosmetic surgery", basis:"policy_exclusion" },
  { tier:"exact", item:"Stem Cell Implantation / Surgery", keywords:"stem cell", basis:"policy_exclusion" },
  // Added 25 Sep 2026. Each row below is an item of the official 68-item List I
  // (02_reference_data/verify_against_official.py, OFFICIAL_68) that
  // did not match even when the bill line used the list's own wording; every
  // keyword is that item's own name or an obvious spelling of it. Deliberately
  // NOT added: plain "gloves", "mask", "sling", "belt", "cream" (too broad:
  // surgical gloves, implant slings and prescribed creams are payable).
  { tier:"exact", item:"Television Charges", keywords:"television charge|television rent|tv charge|tv rent|cable tv" },
  { tier:"exact", item:"Mortuary Charges", keywords:"mortuary" },
  { tier:"exact", item:"Extra Diet of Patient", keywords:"extra diet" },
  { tier:"exact", item:"Private Nurses Charges / Special Nursing Charges", keywords:"private nurse|private nursing|special nurse|special nursing" },
  { tier:"exact", item:"Abdominal Binder", keywords:"abdominal binder" },
  { tier:"exact", item:"Lumbo Sacral Belt", keywords:"lumbo sacral belt|lumbosacral belt|ls belt" },
  { tier:"exact", item:"Pelvic Traction Belt", keywords:"pelvic traction belt" },
  { tier:"exact", item:"Nimbus Bed / Water Bed / Air Bed Charges", keywords:"nimbus bed|water bed|air bed" },
  { tier:"exact", item:"Spirometer", keywords:"spirometer|spirometre" },
  { tier:"exact", item:"Sugar Free Tablets", keywords:"sugar free tablet|sugar free tab" },
  { tier:"exact", item:"Vasofix Safety", keywords:"vasofix safety" },
  { tier:"exact", item:"Leggings", keywords:"legging" },
  { tier:"exact", item:"Pan Can", keywords:"pan can" },
  { tier:"exact", item:"Blood Grouping and Cross Matching of Donors Samples", keywords:"cross matching of donor|crossmatching of donor|cross match of donor" },
  // Not the same as the list: a policy may cover these, so they are only "confirm with your insurer".
  { tier:"review", item:"Food Charges (only non-patient food is excluded)", keywords:"food charge" },
  { tier:"review", item:"Ambulance (excluded unless your policy covers it)", keywords:"ambulance" }
];
// `basis` (unset = "list_i"): these 7 rows are IRDAI's standardized *policy
// exclusions* (Excl-series), not List I non-medical items — still non-payable,
// but citing them as "IRDAI List I" names the wrong document. Verified against
// the official list; see 02_reference_data/IRDAI_VERIFICATION.md.
// 14 of nppa_ceilings.csv's 16 rows — every row currently in force. The two
// excluded are the superseded (pre-1 Apr 2026) stent ceilings: the matcher
// below has no date logic, so a superseded row with the same keywords as its
// current replacement would just sit dead in the array, never reached,
// because the current row is checked first and always wins. Listing it
// anyway would look like date-awareness that isn't actually there.
//
// Order matters: the matcher takes the first row whose keyword appears in
// the line and stops, so a revision or variant row must be listed before
// the generic row it could otherwise be swallowed by (a "REVISION FEMORAL
// COMPONENT" line also contains the plain "femoral component" keyword).
const NPPA = [
  { item:"Knee revision — Femoral component", ceiling:62770, gst:"plus 5% GST", grade:"verify", kw:["revision femoral","femoral revision"] },
  { item:"Knee revision — Tibial component", ceiling:31220, gst:"plus 5% GST", grade:"verify", kw:["revision tibial","tibial revision"] },
  { item:"Knee revision — Articulating surface", ceiling:15870, gst:"plus 5% GST", grade:"verify", kw:["revision articulating","revision insert"] },
  { item:"Knee — Femoral component, High Flex", ceiling:25860, gst:"plus 5% GST", grade:"verify", kw:["femoral component high flex","high flex femoral"] },
  { item:"Knee — Femoral component, Cobalt Chromium", ceiling:24090, gst:"plus 5% GST", grade:"verify", kw:["femoral component cobalt","cobalt chrome femoral","cocr femoral"] },
  { item:"Knee — Femoral component (Ti / Oxidised Zirconium)", ceiling:38740, gst:"plus 5% GST", grade:"verify", kw:["femoral component"] },
  { item:"Knee — Tibial component, Cobalt Chromium", ceiling:16990, gst:"plus 5% GST", grade:"verify", kw:["tibial component cobalt","cobalt chrome tibial","cocr tibial"] },
  { item:"Knee — Tibial component (Ti / Oxidised Zirconium)", ceiling:24280, gst:"plus 5% GST", grade:"verify", kw:["tibial component"] },
  { item:"Knee — Tibial tray + insert, polyethylene", ceiling:12960, gst:"plus 5% GST", grade:"verify", kw:["tibial tray polyethylene","poly tibial tray","tibial tray insert"] },
  { item:"Knee — Tibial tray + insert, metallic", ceiling:26546, gst:"plus 5% GST", grade:"verify", kw:["tibial tray metallic","metal tibial tray"] },
  { item:"Knee — Articulating surface / insert", ceiling:9550, gst:"plus 5% GST", grade:"verify", kw:["articulating surface","tibial insert"] },
  { item:"Knee — Patella", ceiling:4090, gst:"plus 5% GST", grade:"verify", kw:["patella component","patella implant"] },
  { item:"Coronary stent — Bare Metal Stent (BMS)", ceiling:10762.15, gst:"exclusive of GST", grade:"verified", kw:["bare metal stent","bms stent"] },
  { item:"Coronary stent — Drug Eluting Stent (DES)", ceiling:39186.03, gst:"exclusive of GST", grade:"verified", kw:["drug eluting stent","des stent","coronary stent"] },
];
// grade "verified" = independently confirmed against the NPPA notification.
// grade "verify" = the knee-implant ceiling itself is real (NPPA order, extended
// to Nov 2026 per 02_reference_data/nppa_ceilings.csv) but this project has not
// independently re-confirmed it — so the app must not assert it as a settled
// "statutory violation" the way it can for the two verified stent ceilings.

// Full IS 19493:2025 header registry — matches 03_code/completeness.js's
// HEADER_FIELDS exactly (23 mandatory + 3 conditional = 26), so the browser
// app and the Node test tool no longer check two different standards under
// the same name. A conditional field never counts as "missing" — same rule
// completeness.js already uses.
const IS19493_HEADER = [
  ["hospital_name","Hospital name","mandatory"],
  ["hospital_address","Hospital address","mandatory"],
  ["hospital_gstin","Hospital GSTIN (15-digit)","mandatory"],
  ["hospital_contact","Hospital phone / email","mandatory"],
  ["hospital_registration","Registration / licence number","mandatory"],
  ["hospital_accreditation","Accreditation details (e.g. NABH)","conditional"],
  ["bill_number","Unique bill number","mandatory"],
  ["bill_datetime","Bill date & time","mandatory"],
  ["patient_name","Patient name","mandatory"],
  ["patient_age","Patient age","mandatory"],
  ["patient_gender","Patient gender","mandatory"],
  ["patient_hospital_id","Hospital patient ID / IP no.","mandatory"],
  ["patient_uhid","UHID / ABHA","mandatory"],
  ["patient_address","Patient address","mandatory"],
  ["patient_gstin","Patient GSTIN","conditional"],
  ["admission_datetime","Admission date & time","mandatory"],
  ["discharge_datetime","Discharge date & time","mandatory"],
  ["admission_type","Admission type","mandatory"],
  ["gross_amount","Gross amount","mandatory"],
  ["discount_amount","Discount","mandatory"],
  ["tax_amount","Taxes","mandatory"],
  ["net_payable","Net payable","mandatory"],
  ["payment_mode","Payment mode","mandatory"],
  ["insurance_info","Insurance / TPA coverage info","conditional"],
  ["patient_signature","Patient / next-of-kin signature","mandatory"],
  ["authorised_signature","Authorised signatory","mandatory"],
];
const GSTIN_RE = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9][A-Z0-9]{2}$/;

const money = n => Math.round((Number(n)+Number.EPSILON)*100)/100;
/* checks */
// Whole-word matching. The old substring test flagged COMBIFLAM (a medicine)
// as "Comb", APRONAX as "Apron" and ANAESTHETIC as "Aesthetic" (a policy
// exclusion) — and those went into a letter to the insurer as IRDAI List I
// items. Text and keywords are lowercased, punctuation becomes a space (so
// TOOTH-BRUSH and NAME-TAG match), and a keyword must match whole words, with an
// optional plural s/es. An entry may carry a "not" list: words that, if present,
// mean the line is something else (e.g. a spinal-cage spacer is not an inhaler spacer).
const _normTxt=s=>' '+String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()+' ';
const _hasWord=(t,k)=>t.includes(' '+k+' ')||t.includes(' '+k+'s ')||t.includes(' '+k+'es ');
let _matchIndex=null;
function bestMatch(text){
  const t=_normTxt(text); let best=null;
  _matchIndex=_matchIndex||NON_PAYABLE.map(e=>({e,
    kws:e.keywords.split('|').map(k=>_normTxt(k).trim()).filter(Boolean),
    not:(e.not||'').split('|').map(k=>_normTxt(k).trim()).filter(Boolean)}));
  for(const {e,kws,not} of _matchIndex){
    if(not.some(n=>_hasWord(t,n))) continue;
    for(const k of kws){
      if(!_hasWord(t,k)) continue;
      const c={e,kw:k,rank:e.tier==='exact'?2:1,len:k.length};
      if(!best||c.rank>best.rank||(c.rank===best.rank&&c.len>best.len)) best=c;
    }
  }
  return best;
}
// Amounts normally arrive as JSON numbers, but a photo can yield text like
// "1,260.00" or "₹ 500". Plain comma / rupee text is read. Anything ambiguous
// (parentheses, CR/DR suffixes) is NOT guessed: it is counted, so the report can
// say how many amounts were left out instead of silently treating them as 0.
function parseAmount(v){
  if(v==null||v==='') return {n:null,bad:false};
  if(typeof v==='number') return Number.isFinite(v)?{n:v,bad:false}:{n:null,bad:true};
  const s=String(v).trim().replace(/^(?:₹|rs\.?|inr)\s*/i,'').replace(/,/g,'').replace(/\s+/g,'');
  return /^-?\d+(\.\d+)?$/.test(s)?{n:+s,bad:false}:{n:null,bad:true};
}
// NPPA ceilings exclude GST, so a price a few percent above the ceiling can be
// the ceiling plus GST. ASSUMPTION: 5% — the knee-implant notification says
// "plus 5% GST", but the rate that applies to stents has not been confirmed from
// a primary source (CBIC) — until it is, nothing between the ceiling and
// ceiling x 1.05 is ever reported as a finding; it only asks "does the price
// include GST?".
const NPPA_GST_FACTOR=1.05;
// Knee-implant ceilings were published as valid until 15 Nov 2026
// (02_reference_data/nppa_ceilings.csv). After that the copy asks the user to
// check for a newer notification instead of relying on the number.
const NPPA_KNEE_VALID_TO=Date.UTC(2026,10,15,23,59,59);
// "femoral component" also names a HIP part; a knee ceiling must never be
// applied to it.
const HIP_WORDS=/\b(hip|acetabul\w*|bipolar|unipolar|thr|stem|neck|head)\b/;
function analyse(data,now){
  let unreadable=0;
  const amt=v=>{ const p=parseAmount(v); if(p.bad) unreadable++; return p.n; };
  const lines=(data.line_items||[]).map(l=>{
    // Only the line total (and the printed gross) feed a sum, so only those count
    // as "amounts that could not be read". Quantity and rate text such as
    // "2 Nos" or "500/-" is read if it can be and ignored if it cannot.
    let q=parseAmount(l.quantity).n; const tot=amt(l.total), rate=parseAmount(l.rate).n;
    if(tot!=null&&tot<0&&q!=null&&q>0) q=-Math.abs(q);
    return {item:String(l.item||''),unit:l.unit??null,quantity:q,rate,total:tot,section:l.section||l.category||null};
  });
  const H=data.header||{};
  // A credit line (a refund, return or discount shown as a negative amount) is
  // not a charge, and a charge cancelled by an equal credit line is not one
  // either: neither is matched against the lists, so a refunded item can never
  // appear in the letter as something to explain.
  const baseName=s=>String(s).toLowerCase().replace(/\b(refund(ed)?|return(ed)?|reversal|reversed|credit(ed)?|cancel(l?ed)?)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim();
  const credit=new Set(), cancelled=new Set();
  lines.forEach((l,i)=>{ if(l.total==null||l.total>=0) return; credit.add(i);
    const j=lines.findIndex((p,pj)=>p.total>0&&!cancelled.has(pj)&&Math.abs(p.total+l.total)<0.005&&baseName(p.item)===baseName(l.item));
    if(j>=0) cancelled.add(j); });
  const exact=[],review=[];
  lines.forEach((l,i)=>{ if(credit.has(i)||cancelled.has(i)) return; const m=bestMatch(l.item); if(!m) return;
    (m.e.tier==='exact'?exact:review).push({...l,matched:m.e.item,basis:m.e.basis||'list_i'}); });
  const sum=a=>money(a.reduce((s,r)=>s+(r.total||0),0));
  const lineSum=sum(lines);
  let recon=null; const g=amt(H.gross_amount);
  const reconCompared=g!=null;   // no printed total read => "not compared", never "clear"
  if(g!=null){ const d=money(g-lineSum); if(Math.abs(d)>=1) recon={diff:d,gross:money(g),lineSum}; }
  // Repeated charges: same item text and same amount. Ignored: blank items and
  // zero/missing amounts (a repeated 0.00 row is layout, not a double charge).
  // A charge that was reversed (a matching negative line) is netted out — that
  // is a correction, not a duplicate. Recurring services (room rent, daily
  // visits) can legitimately repeat, so the wording asks the user to check.
  const keyOf=(item,amount)=>item.trim().toLowerCase()+'|'+amount.toFixed(2);
  const pos={},neg={};
  lines.forEach(l=>{ if(!l.item.trim()||l.total==null||l.total===0) return;
    if(l.total>0) pos[keyOf(l.item,l.total)]=(pos[keyOf(l.item,l.total)]||0)+1;
    else neg[keyOf(l.item,-l.total)]=(neg[keyOf(l.item,-l.total)]||0)+1; });
  const dups=[];
  lines.forEach(l=>{ if(!l.item.trim()||l.total==null||l.total<=0) return;
    const k=keyOf(l.item,l.total), net=(pos[k]||0)-(neg[k]||0);
    if(net>1&&!dups.find(d=>d.k===k)) dups.push({k,item:l.item,amount:l.total,n:net}); });
  const missing=[],malformed=[];
  // A placeholder is not a value. "Provisional Bill" is truthy and non-blank,
  // so the old isBlank-only test let it through as "present" — this bill is
  // never the final numbered record IS 19493 expects, and that's a real
  // finding, not a reading error.
  const PLACEHOLDER_RE=/^(provisional|draft|temp(orary)?|sample|test|not\s*final)\b/i;
  // Signature fields come back as booleans, not strings — the generic blank
  // test below would read `false` as a non-empty value and call it present.
  const BOOL_FIELDS=new Set(["patient_signature","authorised_signature"]);
  // A blank field can mean two different things, and only one is a finding.
  // "missing" = the hospital didn't print it. "redacted" = we blacked it out
  // ourselves before analysis (set on data._redacted_header_fields, as the
  // real test bill is) — nothing can be concluded from that, and it must
  // never be counted as the hospital's failure. Conditional fields (per
  // IS19493_HEADER's third column) never count as missing either, matching
  // 03_code/completeness.js.
  const redactedSet=new Set(data._redacted_header_fields||[]);
  const redacted=[];
  for(const [k,label,sev] of IS19493_HEADER){
    const v=H[k];
    const blank=BOOL_FIELDS.has(k) ? v!==true
      : (v==null||String(v).trim()===''||/^(n\/?a|nil|none|-|--)$/i.test(String(v).trim()));
    if(blank){
      if(redactedSet.has(k)){ if(sev==='mandatory') redacted.push(label); continue; }   // we removed it — not assessable, not the hospital's fault
      if(sev==='mandatory') missing.push(label);
    }
    else if(k==='bill_number'&&PLACEHOLDER_RE.test(String(v).trim())) missing.push(`${label} (reads "${String(v).trim()}", not a final bill number)`);
    else if(k==='hospital_gstin'&&!GSTIN_RE.test(String(v).replace(/\s/g,''))) malformed.push(label);
  }
  const noUnit = lines.length>0 && lines.every(l=>l.unit==null);
  const nppa=[], nppaGst=[]; let nppaStale=false, nppaCompared=0, nppaSkipped=0;
  const clock=(now instanceof Date?now:new Date()).getTime();
  // A ceiling is for ONE part. A line that is a set, kit or package, or names
  // two parts (femoral + tibial ...), is not comparable and is never flagged.
  const SET_WORDS=/\b(set|kit|package|pkg|combo)\b/;
  const FAMILIES=[/femoral/,/tibial/,/patell/,/insert|articulating/];
  for(let i=0;i<lines.length;i++){ if(credit.has(i)||cancelled.has(i)) continue; const l=lines[i], t=l.item.toLowerCase();
    for(const c of NPPA){ if(c.kw.some(k=>t.includes(k))){
      const knee=c.item.startsWith('Knee');
      if(knee&&HIP_WORDS.test(t)) break;
      if(SET_WORDS.test(t)||FAMILIES.filter(f=>f.test(t)).length>1){ nppaSkipped++; break; }
      // The price per unit. A rate of 0 (the extraction template's placeholder) is
      // "no rate". When both a rate and total/quantity exist the LOWER one is used,
      // so a line total copied into the rate column cannot create a flag.
      const rate=l.rate>0?+l.rate:null, per=(l.total!=null&&l.total>0&&l.quantity)?(+l.total/Math.abs(l.quantity)):null;
      const price=(rate!=null&&per!=null)?Math.min(rate,per):(rate!=null?rate:per);
      if(price!=null) nppaCompared++;
      // At or below the ceiling: never flagged.
      if(price!=null&&price>c.ceiling){
        const stale=knee&&clock>NPPA_KNEE_VALID_TO;
        const row={item:l.item,price:money(price),ceiling:c.ceiling,ref:c.item,gst:c.gst,grade:c.grade||'verify',stale};
        if(price>c.ceiling*NPPA_GST_FACTOR){ nppa.push(row); if(stale) nppaStale=true; }
        else nppaGst.push(row);
      }
      break;
    }}
  }
  // Lines with letters but no English letters (Hindi, Marathi ...) cannot be matched
  // against the English lists; say so instead of implying they were checked.
  const nonLatin=lines.filter(l=>/\p{L}/u.test(l.item)&&!/[A-Za-z]/.test(l.item)).length;
  // Structural hedges only (no invented threshold): one page uploaded, or a
  // page rejected as not-a-bill. Set by the upload flow on the merged object.
  const partial=data._pageCount===1||(data._rejected||0)>0;
  const subtotals = data.printed_subtotals && Object.keys(data.printed_subtotals).length ? data.printed_subtotals : null;
  return {lines,header:H,exact,review,exactSum:sum(exact),reviewSum:sum(review),lineSum,recon,dups,missing,malformed,redacted,noUnit,nppa,nppaGst,nppaStale,nppaCompared,nppaSkipped,nonLatin,subtotals,unreadable,reconCompared,partial,rejected:data._rejected||0,pageCount:data._pageCount||null};
}

module.exports = { NON_PAYABLE, NPPA, IS19493_HEADER, GSTIN_RE, money, bestMatch, parseAmount, analyse };
