/* AUTO-GENERATED by lib/build_checks.js from 06_app/index.html — do not edit.
 * Re-run `node lib/build_checks.js` after changing the reference tables or
 * analyse() in index.html. `node lib/build_checks.js --check` fails if stale. */
const NON_PAYABLE = [
  { tier:"exact", item:"Medical Records", keywords:"medical record" },
  { tier:"exact", item:"TPA Charges", keywords:"tpa charge|insurance processing|insurance charge" },
  { tier:"exact", item:"Certificate Charges", keywords:"certificate charge" },
  { tier:"exact", item:"Medical Certificate", keywords:"medical certificate" },
  { tier:"exact", item:"Birth Certificate", keywords:"birth certificate" },
  { tier:"exact", item:"Photocopies Charges", keywords:"photocopy|photocopies|xerox" },
  { tier:"exact", item:"Courier Charges", keywords:"courier" },
  { tier:"exact", item:"Conveyance Charges", keywords:"conveyance" },
  { tier:"exact", item:"Medico Legal Case Charges", keywords:"medico legal|mlc charge" },
  { tier:"exact", item:"Maintenance Charges", keywords:"maintenance charge" },
  { tier:"exact", item:"Surcharges", keywords:"surcharge" },
  { tier:"exact", item:"Attendant Charges", keywords:"attendant charge" },
  { tier:"exact", item:"Preparation Charges", keywords:"preparation charge" },
  { tier:"review", item:"Service Charges Where Nursing Charge Also Charged", keywords:"service charge" },
  { tier:"review", item:"Referral Doctor's Fees", keywords:"referral doctor|referral fee" },
  { tier:"exact", item:"Savlon", keywords:"savlon" },
  { tier:"review", item:"Micro Shield", keywords:"micro shield|microshield" },
  { tier:"exact", item:"Washing Charges", keywords:"washing charge" },
  { tier:"exact", item:"Laundry Charges", keywords:"laundry" },
  { tier:"exact", item:"Examination Gloves", keywords:"gloves examination|examination glove|exam glove|nitrile glove|glove nitrile|examination medium nitrile" },
  { tier:"review", item:"Surgical Gloves (sterile, in-procedure)", keywords:"surgical glove|glove size|gammex|encore" },
  { tier:"exact", item:"Paper Gloves", keywords:"paper glove" },
  { tier:"exact", item:"Trolly Cover", keywords:"trolley cover|trolly cover" },
  { tier:"exact", item:"Carry Bags", keywords:"carry bag" },
  { tier:"exact", item:"Band Aids, Bandages, Sterile Injections, Needles, Syringes", keywords:"band aid|bandaid" },
  { tier:"exact", item:"Crepe Bandage", keywords:"crepe bandage" },
  { tier:"exact", item:"Hansaplast / Adhesive Bandages", keywords:"hansaplast|adhesive bandage" },
  { tier:"review", item:"Cliniplast", keywords:"cliniplast" },
  { tier:"review", item:"Curapore", keywords:"curapore" },
  { tier:"exact", item:"Eyelet Collar", keywords:"eyelet collar" },
  { tier:"exact", item:"Bed Under Pad Charges", keywords:"under pad|underpad" },
  { tier:"exact", item:"Diaper of Any Type", keywords:"diaper" },
  { tier:"exact", item:"Kidney Tray", keywords:"kidney tray" },
  { tier:"exact", item:"Ounce Glass", keywords:"ounce glass" },
  { tier:"exact", item:"Urometer, Urine Jug", keywords:"urometer|urine jug" },
  { tier:"review", item:"Medicine Box", keywords:"medicine box" },
  { tier:"exact", item:"Thermometer", keywords:"thermometer" },
  { tier:"exact", item:"Towel", keywords:"towel|cosy towel" },
  { tier:"exact", item:"Sanitary Pad", keywords:"sanitary pad" },
  { tier:"exact", item:"Powder", keywords:"talcum powder" },
  { tier:"exact", item:"Moisturiser / Paste / Brush", keywords:"moisturiser|moisturizer" },
  { tier:"exact", item:"Mineral Water", keywords:"mineral water" },
  { tier:"exact", item:"Buds", keywords:"ear bud|cotton bud|buds" },
  { tier:"exact", item:"Barber Charges", keywords:"barber" },
  { tier:"exact", item:"Beauty Services", keywords:"beauty service" },
  { tier:"exact", item:"Baby Food", keywords:"baby food|lactogen|infant food" },
  { tier:"exact", item:"Baby Utilities Charges", keywords:"baby utilities" },
  { tier:"exact", item:"Telephone Charges", keywords:"telephone charge" },
  { tier:"exact", item:"Email / Internet Charges", keywords:"internet charge|email charge|wifi" },
  { tier:"exact", item:"Guest Services", keywords:"guest service" },
  { tier:"exact", item:"Food Charges (Other than Patient's Diet)", keywords:"attendant food|guest food|visitor food" },
  { tier:"exact", item:"Walking Aids Charges", keywords:"walking aid|walker charge" },
  { tier:"review", item:"Commode", keywords:"commode" },
  { tier:"review", item:"Oxygen Cylinder (usage outside hospital)", keywords:"oxygen cylinder" },
  { tier:"exact", item:"Oxygen Mask", keywords:"oxygen mask" },
  { tier:"exact", item:"Spacer", keywords:"spacer", not:"cage|interbody|cement|knee|hip|spine|spinal|vertebral|antibiotic|implant" },
  { tier:"exact", item:"Nebulizer Kit", keywords:"nebulizer kit|nebuliser kit|nebulisation kit|nebulization kit" },
  { tier:"exact", item:"Steam Inhaler", keywords:"steam inhaler" },
  { tier:"exact", item:"Arm Sling", keywords:"arm sling|armsling" },
  { tier:"exact", item:"Cervical Collar", keywords:"cervical collar" },
  { tier:"exact", item:"Ambulance Collar", keywords:"ambulance collar" },
  { tier:"exact", item:"Ambulance Equipment", keywords:"ambulance equipment" },
  { tier:"exact", item:"Splint", keywords:"splint" },
  { tier:"exact", item:"Knee Braces", keywords:"knee brace" },
  { tier:"exact", item:"Knee/Shoulder Immobilizer", keywords:"immobilizer|immobiliser" },
  { tier:"exact", item:"Diabetic Foot Wear", keywords:"diabetic footwear|diabetic foot wear" },
  { tier:"exact", item:"Visco Belt Charges", keywords:"visco belt" },
  { tier:"exact", item:"Cold Pack / Hot Pack", keywords:"cold pack|hot pack" },
  { tier:"review", item:"Any Kit With No Details Mentioned", keywords:"kit" },
  { tier:"review", item:"CSSD / Sterilisation Charges", keywords:"cssd|sterilisation charge|sterilization charge" },
  { tier:"review", item:"ECG Electrodes / Leads", keywords:"ecg lead|ecg electrode" },
  { tier:"review", item:"Dressing / Tegaderm film", keywords:"tegaderm|transparent dressing" },
  { tier:"exact", item:"Weight Control Programs / Supplies / Services", keywords:"weight control|obesity program" },
  { tier:"exact", item:"Spectacles / Contact Lenses / Hearing Aids", keywords:"spectacle|contact lens|hearing aid" },
  { tier:"exact", item:"Dental Treatment Not Requiring Hospitalisation", keywords:"dental treatment", basis:"policy_exclusion" },
  { tier:"exact", item:"Hormone Replacement Therapy", keywords:"hormone replacement", basis:"policy_exclusion" },
  { tier:"exact", item:"Home Visit Charges", keywords:"home visit" },
  { tier:"exact", item:"Infertility / Assisted Conception", keywords:"infertility|assisted conception|ivf treatment|ivf cycle|ivf procedure|in vitro fertilisation|in vitro fertilization", basis:"policy_exclusion" },
  { tier:"exact", item:"Obesity Treatment", keywords:"bariatric|obesity treatment", basis:"policy_exclusion" },
  { tier:"exact", item:"Corrective Surgery for Refractive Error", keywords:"lasik|refractive error", basis:"policy_exclusion" },
  { tier:"exact", item:"Donor Screening Charges", keywords:"donor screening" },
  { tier:"exact", item:"Aesthetic Treatment / Surgery", keywords:"aesthetic|cosmetic surgery", basis:"policy_exclusion" },
  { tier:"exact", item:"Stem Cell Implantation / Surgery", keywords:"stem cell", basis:"policy_exclusion" },
  // Added 25 Sep 2026. Each row below is an item of the official 68-item List I
  // (02_reference_data/verify_against_official.py, OFFICIAL_68) that
  // did not match even when the bill line used the list's own wording; every
  // keyword is that item's own name or an obvious spelling of it. Deliberately
  // NOT added: plain "gloves", "mask", "sling", "belt", "cream" (too broad:
  // surgical gloves, implant slings and prescribed creams are payable).
  { tier:"exact", item:"Television Charges", keywords:"television charge|television rent|tv charge|tv rent|cable tv" },
  { tier:"exact", item:"Mortuary Charges", keywords:"mortuary" },
  { tier:"exact", item:"Extra Diet of Patient", keywords:"extra diet" },
  { tier:"exact", item:"Private Nurses Charges", keywords:"private nurse|private nursing" },
  { tier:"exact", item:"Abdominal Binder", keywords:"abdominal binder" },
  { tier:"exact", item:"Lumbo Sacral Belt", keywords:"lumbo sacral belt|lumbosacral belt|ls belt" },
  { tier:"exact", item:"Pelvic Traction Belt", keywords:"pelvic traction belt" },
  { tier:"exact", item:"Nimbus Bed / Water Bed / Air Bed Charges", keywords:"nimbus bed|water bed|air bed" },
  { tier:"exact", item:"Spirometer", keywords:"spirometer|spirometre" },
  { tier:"exact", item:"Sugar Free Tablets", keywords:"sugar free tablet|sugar free tab" },
  { tier:"exact", item:"Vasofix Safety", keywords:"vasofix safety" },
  { tier:"exact", item:"Leggings", keywords:"legging" },
  { tier:"exact", item:"Pan Can", keywords:"pan can" },
  { tier:"exact", item:"Blood Grouping and Cross Matching of Donors Samples", keywords:"cross matching of donor|crossmatching of donor|cross match of donor" },
  // Not the same as the list: a policy may cover these, so they are only "confirm with your insurer".
  { tier:"review", item:"Food Charges (only non-patient food is excluded)", keywords:"food charge" },
  { tier:"review", item:"Ambulance (excluded unless your policy covers it)", keywords:"ambulance" }
];
// `basis` (unset = "list_i"): these 7 rows are IRDAI's standardized *policy
// exclusions* (Excl-series), not List I non-medical items — still non-payable,
// but citing them as "IRDAI List I" names the wrong document. Verified against
// the official list; see 02_reference_data/IRDAI_VERIFICATION.md.
// 14 of nppa_ceilings.csv's 16 rows — every row currently in force. The two
// excluded are the superseded (pre-1 Apr 2026) stent ceilings: the matcher
// below has no date logic, so a superseded row with the same keywords as its
// current replacement would just sit dead in the array, never reached,
// because the current row is checked first and always wins. Listing it
// anyway would look like date-awareness that isn't actually there.
//
// Order matters: the matcher takes the first row whose keyword appears in
// the line and stops, so a revision or variant row must be listed before
// the generic row it could otherwise be swallowed by (a "REVISION FEMORAL
// COMPONENT" line also contains the plain "femoral component" keyword).
// `req` (revision rows only) matches whole words in ANY order: "FEMORAL
// COMPONENT REVISION" has neither "revision femoral" nor "femoral revision"
// as a phrase, so it used to fall through to the generic femoral row and be
// compared with the lower (non-revision) ceiling — a false flag on a
// correctly priced revision implant (R11).
const NPPA = [
  { item:"Knee revision — Femoral component", ceiling:62770, gst:"plus 5% GST", grade:"verify", kw:["revision femoral","femoral revision"], req:[["revision","femoral"]] },
  { item:"Knee revision — Tibial component", ceiling:31220, gst:"plus 5% GST", grade:"verify", kw:["revision tibial","tibial revision"], req:[["revision","tibial"]] },
  { item:"Knee revision — Articulating surface", ceiling:15870, gst:"plus 5% GST", grade:"verify", kw:["revision articulating","revision insert"], req:[["revision","articulating"],["revision","insert"]] },
  { item:"Knee — Femoral component, High Flex", ceiling:25860, gst:"plus 5% GST", grade:"verify", kw:["femoral component high flex","high flex femoral"] },
  { item:"Knee — Femoral component, Cobalt Chromium", ceiling:24090, gst:"plus 5% GST", grade:"verify", kw:["femoral component cobalt","cobalt chrome femoral","cocr femoral"] },
  { item:"Knee — Femoral component (Ti / Oxidised Zirconium)", ceiling:38740, gst:"plus 5% GST", grade:"verify", kw:["femoral component"] },
  { item:"Knee — Tibial component, Cobalt Chromium", ceiling:16990, gst:"plus 5% GST", grade:"verify", kw:["tibial component cobalt","cobalt chrome tibial","cocr tibial"] },
  { item:"Knee — Tibial component (Ti / Oxidised Zirconium)", ceiling:24280, gst:"plus 5% GST", grade:"verify", kw:["tibial component"] },
  { item:"Knee — Tibial tray + insert, polyethylene", ceiling:12960, gst:"plus 5% GST", grade:"verify", kw:["tibial tray polyethylene","poly tibial tray","tibial tray insert"] },
  { item:"Knee — Tibial tray + insert, metallic", ceiling:26546, gst:"plus 5% GST", grade:"verify", kw:["tibial tray metallic","metal tibial tray"] },
  { item:"Knee — Articulating surface / insert", ceiling:9550, gst:"plus 5% GST", grade:"verify", kw:["articulating surface","tibial insert"] },
  { item:"Knee — Patella", ceiling:4090, gst:"plus 5% GST", grade:"verify", kw:["patella component","patella implant"] },
  { item:"Coronary stent — Bare Metal Stent (BMS)", ceiling:10762.15, gst:"exclusive of GST", grade:"verified", kw:["bare metal stent","bms stent"] },
  { item:"Coronary stent — Drug Eluting Stent (DES)", ceiling:39186.03, gst:"exclusive of GST", grade:"verified", kw:["drug eluting stent","des stent","coronary stent"] },
];
// grade "verified" = independently confirmed against the NPPA notification.
// grade "verify" = the knee-implant ceiling itself is real (NPPA order, extended
// to Nov 2026 per 02_reference_data/nppa_ceilings.csv) but this project has not
// independently re-confirmed it — so the app must not assert it as a settled
// "statutory violation" the way it can for the two verified stent ceilings.
// IRDAI's Guidelines on Standardization in Health Insurance (Modification,
// 27 September 2019) list three MORE tables besides List I (read on irdai.gov.in,
// 27 Sep 2026): items that must already be included in another charge, not
// billed as their own line —
//   List II  = should be part of ROOM charges
//   List III = should be part of the PROCEDURE/surgery charges
//   List IV  = should be part of the overall TREATMENT cost
// This is a different point from List I: List I is about what an insurer need
// not pay; these are about whether the hospital should have billed the item as
// a separate line at all. All 78 official item names are covered here, in one
// table since the matching logic is identical; `list` records which of the
// three it came from for the citation. A few rows fold more than one official
// name together (the Baby Charges group, Urine Container/Bag, Shoe/Foot Cover,
// Face/Flexi Mask, Gauze/Gauze Soft) the same way NON_PAYABLE already does.
// Generated into 02_reference_data/irdai_subsumed_lists_ii_iv.csv by
// lib/sync_reference.js; lib/test_reference.js checks the two agree and that
// every official item is covered.
const SUBSUMED = [
  { list:"II", item:"Baby Charges", keywords:"baby charge|baby set|baby bottle|feeding bottle|baby vaccine|vaccine charges for baby" },
  { list:"II", item:"Hand Wash", keywords:"hand wash" },
  { list:"II", item:"Shoe Cover / Foot Cover", keywords:"shoe cover|foot cover" },
  { list:"II", item:"Caps", keywords:"surgical cap|theatre cap" },
  { list:"II", item:"Cradle Charges", keywords:"cradle" },
  { list:"II", item:"Comb", keywords:"comb" },
  { list:"II", item:"Eau-De-Cologne / Room Freshners", keywords:"room freshener|room freshner|cologne" },
  { list:"II", item:"Gown", keywords:"gown" },
  { list:"II", item:"Slippers", keywords:"slipper" },
  { list:"II", item:"Tissue Paper", keywords:"tissue paper" },
  { list:"II", item:"Tooth Paste", keywords:"tooth paste|toothpaste" },
  { list:"II", item:"Tooth Brush", keywords:"tooth brush|toothbrush" },
  { list:"II", item:"Bed Pan", keywords:"bed pan|bedpan" },
  { list:"II", item:"Face Mask / Flexi Mask", keywords:"face mask|flexi mask|surgical mask" },
  { list:"II", item:"Hand Holder", keywords:"hand holder" },
  { list:"II", item:"Sputum Cup", keywords:"sputum cup" },
  { list:"II", item:"Disinfectant Lotions", keywords:"disinfectant lotion" },
  { list:"II", item:"Luxury Tax", keywords:"luxury tax" },
  { list:"II", item:"HVAC Charges", keywords:"hvac" },
  { list:"II", item:"House Keeping Charges", keywords:"house keeping|housekeeping" },
  { list:"II", item:"Air Conditioner Charges", keywords:"air conditioner charge|ac charge" },
  { list:"II", item:"IM/IV Injection Charges", keywords:"im injection charge|iv injection charge|injection administration charge" },
  { list:"II", item:"Clean Sheet", keywords:"clean sheet" },
  { list:"II", item:"Blanket / Warmer Blanket", keywords:"blanket" },
  { list:"II", item:"Admission Kit", keywords:"admission kit" },
  { list:"II", item:"Diabetic Chart Charges", keywords:"diabetic chart" },
  { list:"II", item:"Documentation Charges / Administrative Expenses", keywords:"documentation charge|administrative expense|admin charge" },
  { list:"II", item:"Discharge Procedure Charges", keywords:"discharge procedure|discharge charge" },
  { list:"II", item:"Daily Chart Charges", keywords:"daily chart" },
  { list:"II", item:"Entrance Pass / Visitors Pass Charges", keywords:"visitor pass|entrance pass" },
  { list:"II", item:"Expenses Related to Prescription on Discharge", keywords:"prescription on discharge|discharge prescription charge" },
  { list:"II", item:"File Opening Charges", keywords:"file opening charge" },
  { list:"II", item:"Incidental Expenses / Misc. Charges", keywords:"incidental expense|miscellaneous charge|misc charge" },
  { list:"II", item:"Patient Identification Band / Name Tag", keywords:"identification band|name tag|id band" },
  { list:"II", item:"Pulseoxymeter Charges", keywords:"pulseoxymeter|pulse oximeter charge|spo2 probe|spo2 sensor" },
  { list:"III", item:"Hair Removal Cream", keywords:"hair removal cream" },
  { list:"III", item:"Disposable Razor Charges", keywords:"disposable razor|disposable razors|disposables razors|razor charge" },
  { list:"III", item:"Eye Pad", keywords:"eye pad" },
  { list:"III", item:"Eye Shield", keywords:"eye shield|eye sheild" },
  { list:"III", item:"Camera Cover", keywords:"camera cover" },
  { list:"III", item:"DVD, CD Charges", keywords:"dvd charge|cd charge" },
  { list:"III", item:"Gauze / Gauze Soft", keywords:"gauze|gauze soft|gauge soft|gause soft" },
  { list:"III", item:"Ward and Theatre Booking Charges", keywords:"ward booking charge|theatre booking charge|ot booking charge" },
  { list:"III", item:"Arthroscopy and Endoscopy Instruments", keywords:"arthroscopy instrument|endoscopy instrument" },
  { list:"III", item:"Microscope Cover", keywords:"microscope cover" },
  { list:"III", item:"Surgical Blades / Harmonic Scalpel / Shaver", keywords:"surgical blade|harmonic scalpel|shaver blade" },
  { list:"III", item:"Surgical Drill", keywords:"surgical drill" },
  { list:"III", item:"Eye Kit", keywords:"eye kit" },
  { list:"III", item:"Eye Drape", keywords:"eye drape" },
  { list:"III", item:"X-Ray Film", keywords:"x ray film|xray film" },
  { list:"III", item:"Boyles Apparatus Charges", keywords:"boyles apparatus" },
  { list:"III", item:"Cotton", keywords:"cotton roll|absorbent cotton" },
  { list:"III", item:"Cotton Bandage", keywords:"cotton bandage" },
  { list:"III", item:"Surgical Tape", keywords:"surgical tape" },
  { list:"III", item:"Apron", keywords:"apron" },
  { list:"III", item:"Tourniquet", keywords:"tourniquet|torniquet" },
  { list:"III", item:"Orthobundle / Gynaec Bundle", keywords:"orthobundle|ortho bundle|gynaec bundle|gynaecology bundle" },
  { list:"IV", item:"Admission/Registration Charges", keywords:"admission service|registration charge|admission charge" },
  { list:"IV", item:"Hospitalisation for Evaluation / Diagnostic Purpose", keywords:"evaluation only|diagnostic admission|hospitalisation for evaluation|diagnostic purpose" },
  { list:"IV", item:"Urine Container / Urine Bag", keywords:"urine container|urine bag" },
  { list:"IV", item:"Blood Reservation Charges / Ante Natal Booking", keywords:"blood reservation|ante natal booking" },
  { list:"IV", item:"BiPAP Machine", keywords:"bipap" },
  { list:"IV", item:"CPAP / CAPD Equipment", keywords:"cpap|capd equipment" },
  { list:"IV", item:"Infusion Pump", keywords:"infusion pump" },
  { list:"IV", item:"Hydrogen Peroxide / Spirit / Disinfectants", keywords:"hydrogen peroxide" },
  { list:"IV", item:"Nutrition Planning / Dietician Charges", keywords:"dietician charge|nutrition planning|diet counselling|diet counseling" },
  { list:"IV", item:"HIV Kit", keywords:"hiv kit" },
  { list:"IV", item:"Antiseptic Mouthwash", keywords:"antiseptic mouthwash" },
  { list:"IV", item:"Lozenges", keywords:"lozenges|lozenge" },
  { list:"IV", item:"Mouth Paint", keywords:"mouth paint" },
  { list:"IV", item:"Vaccination Charges", keywords:"vaccination charge" },
  { list:"IV", item:"Alcohol Swabs", keywords:"alco swab|alcohol swab|alcohol gauze" },
  { list:"IV", item:"Scrub Solution / Sterillium", keywords:"sterillium|scrub solution|propanol|alcorub|povidone scrub|hand rub" },
  { list:"IV", item:"Glucometer & Strips", keywords:"glucometer|glucose strip" },
];

// Insurance Ombudsman offices (R13). Read on 5 Oct 2026 from the Council for
// Insurance Ombudsmen's own contact page, cioins.co.in/Ombudsman — the list that
// page DISPLAYS. The same page also carries a second, permanently hidden copy
// with different addresses and names for several offices (it still says
// "Orissa" and "Uttaranchal"); that copy is stale and is not used.
// Addresses, phone and email are copied as published (only line breaks and
// spacing tidied). The Ombudsman's own name is left out: it changes, and
// writing to "the Insurance Ombudsman" at the office is enough.
// `states` = states/UTs the office covers in full. `part` = states it covers
// only in part; for those the app shows every candidate office with the page's
// own jurisdiction wording, word for word, rather than guessing a district
// mapping (the page's Uttar Pradesh district lists use older names such as
// Allahabad and Faizabad and do not name every district).
const OMBUDSMAN_READ_ON='2026-10-05';
const OMBUDSMAN = [
  { office:"Ahmedabad", address:"Jeevan Prakash Building, 6th floor, Tilak Marg, Relief Road, Ahmedabad – 380 001", tel:"079 - 25501201/02", email:"oio.ahmedabad@cioins.co.in",
    states:["Gujarat","Dadra and Nagar Haveli and Daman and Diu"], part:[], jurisdiction:"Gujarat, Dadra & Nagar Haveli, Daman and Diu." },
  { office:"Bengaluru", address:"Jeevan Soudha Building, PID No. 57-27-N-19, Ground Floor, 19/19, 24th Main Road, JP Nagar, Ist Phase, Bengaluru – 560 078", tel:"080 - 26652048 / 26652049", email:"oio.bengaluru@cioins.co.in",
    states:["Karnataka"], part:[], jurisdiction:"Karnataka." },
  { office:"Bhopal", address:"1st floor, \"Jeevan Shikha\", 60-B, Hoshangabad Road, Opp. Gayatri Mandir, Arera Hills, Bhopal – 462 011", tel:"0755 - 2769201 / 2769202 / 2769203", email:"oio.bhopal@cioins.co.in",
    states:["Madhya Pradesh","Chhattisgarh"], part:[], jurisdiction:"Madhya Pradesh, Chhattisgarh." },
  { office:"Bhubaneswar", address:"62, Forest park, Bhubaneswar – 751 009", tel:"0674 - 2596461 / 2596455 / 2596429 / 2596003", email:"oio.bhubaneswar@cioins.co.in",
    states:["Odisha"], part:[], jurisdiction:"Odisha." },
  { office:"Chandigarh", address:"Jeevan Deep Building, SCO 20-27, Ground Floor, Sector-17 A, Chandigarh – 160 017", tel:"0172-2706468", email:"oio.chandigarh@cioins.co.in",
    states:["Punjab","Himachal Pradesh","Jammu and Kashmir","Ladakh","Chandigarh"], part:["Haryana"], jurisdiction:"Punjab, Haryana (excluding Gurugram, Faridabad, Sonepat and Bahadurgarh), Himachal Pradesh, Union Territories of Jammu & Kashmir, Ladakh & Chandigarh." },
  { office:"Chennai", address:"Fatima Akhtar Court, 4th Floor, 453, Anna Salai, Teynampet, Chennai – 600 018", tel:"044 - 24333668 / 24333678", email:"oio.chennai@cioins.co.in",
    states:["Tamil Nadu"], part:["Puducherry"], jurisdiction:"Tamil Nadu, Puducherry Town and Karaikal (which are part of Puducherry)." },
  { office:"Delhi", address:"2/2 A, Universal Insurance Building, Asaf Ali Road, New Delhi – 110 002", tel:"011 - 46013992 / 23213504 / 23232481", email:"oio.delhi@cioins.co.in",
    states:["Delhi"], part:["Haryana"], jurisdiction:"Delhi & following Districts of Haryana - Gurugram, Faridabad, Sonepat & Bahadurgarh." },
  { office:"Guwahati", address:"Jeevan Nivesh, 5th Floor, Near Pan Bazar, S.S. Road, Guwahati – 781 001 (Assam)", tel:"0361 - 2632204 / 2602205 / 2631307", email:"oio.guwahati@cioins.co.in",
    states:["Assam","Meghalaya","Manipur","Mizoram","Arunachal Pradesh","Nagaland","Tripura"], part:[], jurisdiction:"Assam, Meghalaya, Manipur, Mizoram, Arunachal Pradesh, Nagaland and Tripura." },
  { office:"Hyderabad", address:"6-2-46, 1st floor, \"Moin Court\", Lane Opp. Hyundai Showroom, A. C. Guards, Lakdi-Ka-Pool, Hyderabad – 500 004", tel:"040 - 23312122 / 23376991 / 23376599 / 23328709 / 23325325", email:"oio.hyderabad@cioins.co.in",
    states:["Andhra Pradesh","Telangana"], part:["Puducherry"], jurisdiction:"Andhra Pradesh, Telangana, Yanam and part of Union Territory of Puducherry." },
  { office:"Jaipur", address:"Jeevan Nidhi – II Bldg., Gr. Floor, Bhawani Singh Marg, Jaipur – 302 005", tel:"0141-2740363", email:"oio.jaipur@cioins.co.in",
    states:["Rajasthan"], part:[], jurisdiction:"Rajasthan." },
  { office:"Kochi", address:"10th Floor, Jeevan Prakash, LIC Building, Opp. to Maharaja's College Ground, M.G. Road, Kochi – 682 011", tel:"0484 - 2358759", email:"oio.ernakulam@cioins.co.in",
    states:["Kerala","Lakshadweep"], part:["Puducherry"], jurisdiction:"Kerala, Lakshadweep, Mahe - a part of Union Territory of Puducherry." },
  { office:"Kolkata", address:"Hindustan Bldg. Annexe, 7th Floor, 4, C.R. Avenue, Kolkata – 700 072", tel:"033 - 22124339 / 22124341", email:"oio.kolkata@cioins.co.in",
    states:["West Bengal","Sikkim","Andaman and Nicobar Islands"], part:[], jurisdiction:"West Bengal, Sikkim, Andaman & Nicobar Islands." },
  { office:"Lucknow", address:"6th Floor, Jeevan Bhawan, Phase-II, Nawal Kishore Road, Hazratganj, Lucknow – 226 001", tel:"0522 - 4002082 / 3500613", email:"oio.lucknow@cioins.co.in",
    states:[], part:["Uttar Pradesh"], jurisdiction:"Districts of Uttar Pradesh: Lalitpur, Jhansi, Mahoba, Hamirpur, Banda, Chitrakoot, Allahabad, Mirzapur, Sonbhabdra, Fatehpur, Pratapgarh, Jaunpur, Varanasi, Gazipur, Jalaun, Kanpur, Lucknow, Unnao, Sitapur, Lakhimpur, Bahraich, Barabanki, Raebareli, Sravasti, Gonda, Faizabad, Amethi, Kaushambi, Balrampur, Basti, Ambedkarnagar, Sultanpur, Maharajgang, Santkabirnagar, Azamgarh, Kushinagar, Gorkhpur, Deoria, Mau, Ghazipur, Chandauli, Ballia, Sidharathnagar." },
  { office:"Mumbai", address:"3rd Floor, Jeevan Seva Annexe, S. V. Road, Santacruz (W), Mumbai – 400 054", tel:"022 - 69038800/27/29/31/32/33", email:"oio.mumbai@cioins.co.in",
    states:[], part:["Maharashtra"], jurisdiction:"List of wards under Mumbai Metropolitan Region excluding wards in Mumbai – i.e. M/E, M/W, N, S and T covered under Office of Insurance Ombudsman Thane and excluding areas of Navi Mumbai." },
  { office:"Noida", address:"Bhagwan Sahai Palace, 4th Floor, Main Road, Naya Bans, Sector 15, Distt: Gautam Buddh Nagar, U.P. – 201 301", tel:"0120-4027589", email:"oio.noida@cioins.co.in",
    states:["Uttarakhand"], part:["Uttar Pradesh"], jurisdiction:"State of Uttarakhand and the following Districts of Uttar Pradesh: Agra, Aligarh, Bagpat, Bareilly, Bijnor, Budaun, Bulandshehar, Etah, Kannauj, Mainpuri, Mathura, Meerut, Moradabad, Muzaffarnagar, Oraiyya, Pilibhit, Etawah, Farrukhabad, Firozbad, Gautam Buddh nagar, Ghaziabad, Hardoi, Shahjahanpur, Hapur, Shamli, Rampur, Kashganj, Sambhal, Amroha, Hathras, Kanshiramnagar, Saharanpur." },
  { office:"Patna", address:"2nd Floor, Lalit Bhawan, Bailey Road, Patna – 800 001", tel:"0612-2547068", email:"oio.patna@cioins.co.in",
    states:["Bihar","Jharkhand"], part:[], jurisdiction:"Bihar, Jharkhand." },
  { office:"Pune", address:"Jeevan Darshan Bldg., 3rd Floor, C.T.S. No.s. 195 to 198, N.C. Kelkar Road, Narayan Peth, Pune – 411 030", tel:"020-24471175", email:"oio.pune@cioins.co.in",
    states:["Goa"], part:["Maharashtra"], jurisdiction:"State of Goa and State of Maharashtra excluding areas of Navi Mumbai, Thane district, Palghar District, Raigad district & Mumbai Metropolitan Region." },
  { office:"Thane", address:"Jeevan Chintamani Building, 2nd Floor, Near New RTO Office, Louis Wadi, Vasantrao Naik Mahamarg, Thane (West) – 400 604", tel:"022-20812868/69", email:"oio.thane@cioins.co.in",
    states:[], part:["Maharashtra"], jurisdiction:"Area of Navi Mumbai, Thane District, Raigad District, Palghar District and wards of Mumbai, M/East, M/West, N, S and T." },
];
// The 28 states and 8 union territories, as offered in the letter form.
const INDIA_STATES = ["Andaman and Nicobar Islands","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chandigarh","Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand",
  "Karnataka","Kerala","Ladakh","Lakshadweep","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha",
  "Puducherry","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"];
const ombudsmanFor = state => state ? OMBUDSMAN.filter(o=>o.states.includes(state)||o.part.includes(state)) : [];


// Full IS 19493:2025 header registry — matches 03_code/completeness.js's
// HEADER_FIELDS exactly (23 mandatory + 3 conditional = 26), so the browser
// app and the Node test tool no longer check two different standards under
// the same name. A conditional field never counts as "missing" — same rule
// completeness.js already uses.
const IS19493_HEADER = [
  ["hospital_name","Hospital name","mandatory"],
  ["hospital_address","Hospital address","mandatory"],
  ["hospital_gstin","Hospital GSTIN (15-digit)","mandatory"],
  ["hospital_contact","Hospital phone / email","mandatory"],
  ["hospital_registration","Registration / licence number","mandatory"],
  ["hospital_accreditation","Accreditation details (e.g. NABH)","conditional"],
  ["bill_number","Unique bill number","mandatory"],
  ["bill_datetime","Bill date & time","mandatory"],
  ["patient_name","Patient name","mandatory"],
  ["patient_age","Patient age","mandatory"],
  ["patient_gender","Patient gender","mandatory"],
  ["patient_hospital_id","Hospital patient ID / IP no.","mandatory"],
  ["patient_uhid","UHID / ABHA","mandatory"],
  ["patient_address","Patient address","mandatory"],
  ["patient_gstin","Patient GSTIN","conditional"],
  ["admission_datetime","Admission date & time","mandatory"],
  ["discharge_datetime","Discharge date & time","mandatory"],
  ["admission_type","Admission type","mandatory"],
  ["gross_amount","Gross amount","mandatory"],
  ["discount_amount","Discount","mandatory"],
  ["tax_amount","Taxes","mandatory"],
  ["net_payable","Net payable","mandatory"],
  ["payment_mode","Payment mode","mandatory"],
  ["insurance_info","Insurance / TPA coverage info","conditional"],
  ["patient_signature","Patient / next-of-kin signature","mandatory"],
  ["authorised_signature","Authorised signatory","mandatory"],
];
// state code (2 digits) + PAN (5 letters, 4 digits, 1 letter) + entity number
// (1-9, then A-Z) + "Z" (fixed for a regular registration) + 1 check character.
// The old pattern allowed any character in place of the fixed "Z" and
// rejected a valid letter entity number (R11).
const GSTIN_RE = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/;

const money = n => Math.round((Number(n)+Number.EPSILON)*100)/100;
/* checks */
// Whole-word matching. The old substring test flagged COMBIFLAM (a medicine)
// as "Comb", APRONAX as "Apron" and ANAESTHETIC as "Aesthetic" (a policy
// exclusion) — and those went into a letter to the insurer as IRDAI List I
// items. Text and keywords are lowercased, punctuation becomes a space (so
// TOOTH-BRUSH and NAME-TAG match), and a keyword must match whole words, with an
// optional plural s/es. An entry may carry a "not" list: words that, if present,
// mean the line is something else (e.g. a spinal-cage spacer is not an inhaler spacer).
const _normTxt=s=>' '+String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()+' ';
const _hasWord=(t,k)=>t.includes(' '+k+' ')||t.includes(' '+k+'s ')||t.includes(' '+k+'es ');
// Builds and caches the {entry, keywords, not-words} index for one table, the
// first time that table is used, so repeat calls (one per bill line) don't
// re-split every keyword string.
const _matchIndexes=new Map();
function _indexFor(table){
  let idx=_matchIndexes.get(table);
  if(!idx){ idx=table.map(e=>({e,
    kws:e.keywords.split('|').map(k=>_normTxt(k).trim()).filter(Boolean),
    not:(e.not||'').split('|').map(k=>_normTxt(k).trim()).filter(Boolean)})); _matchIndexes.set(table,idx); }
  return idx;
}
function bestMatchIn(text,table){
  const t=_normTxt(text); let best=null;
  for(const {e,kws,not} of _indexFor(table)){
    if(not.some(n=>_hasWord(t,n))) continue;
    for(const k of kws){
      if(!_hasWord(t,k)) continue;
      const c={e,kw:k,rank:e.tier==='exact'?2:1,len:k.length};
      if(!best||c.rank>best.rank||(c.rank===best.rank&&c.len>best.len)) best=c;
    }
  }
  return best;
}
function bestMatch(text){ return bestMatchIn(text,NON_PAYABLE); }
// Amounts normally arrive as JSON numbers, but a photo can yield text like
// "1,260.00" or "₹ 500". Plain comma / rupee text is read. Anything ambiguous
// (parentheses, CR/DR suffixes) is NOT guessed: it is counted, so the report can
// say how many amounts were left out instead of silently treating them as 0.
function parseAmount(v){
  if(v==null||v==='') return {n:null,bad:false};
  if(typeof v==='number') return Number.isFinite(v)?{n:v,bad:false}:{n:null,bad:true};
  const s=String(v).trim().replace(/^(?:₹|rs\.?|inr)\s*/i,'').replace(/,/g,'').replace(/\s+/g,'');
  return /^-?\d+(\.\d+)?$/.test(s)?{n:+s,bad:false}:{n:null,bad:true};
}
// NPPA ceilings exclude GST, so a price a few percent above the ceiling can be
// the ceiling plus GST. ASSUMPTION: 5% — the knee-implant notification says
// "plus 5% GST", but the rate that applies to stents has not been confirmed from
// a primary source (CBIC) — until it is, nothing between the ceiling and
// ceiling x 1.05 is ever reported as a finding; it only asks "does the price
// include GST?".
const NPPA_GST_FACTOR=1.05;
// Knee-implant ceilings were published as valid until 15 Nov 2026
// (02_reference_data/nppa_ceilings.csv). After that the copy asks the user to
// check for a newer notification instead of relying on the number.
const NPPA_KNEE_VALID_TO=Date.UTC(2026,10,15,23,59,59);
// Stent ceilings: the ones in this table took effect on 1 Apr 2026 (NPPA order
// S.O. 1587(E), 02_reference_data/nppa_ceilings.csv). A bill dated earlier was
// priced under an earlier ceiling that this app does not hold a verified
// figure for, so such a bill is never compared. ASSUMPTION, not confirmed from a
// primary source: the stent ceilings have been revised each 1 April (the CSV
// lists a superseded pre-April-2026 pair), so from 1 Apr 2027 the copy asks the
// user to check for a newer notification.
const NPPA_STENT_FROM=Date.UTC(2026,3,1);
const NPPA_STENT_REVIEW_FROM=Date.UTC(2027,3,1);
// The bill's date as the earliest and latest reading of it. Indian bills write
// DD/MM/YYYY, but 05/06/2026 could also be read month-first, so both readings are
// kept and a check relies on the date only when every reading agrees.
function billDateRange(H){
  for(const k of ['bill_datetime','discharge_datetime','admission_datetime']){
    const s=String((H&&H[k])||'');
    let m=/\b(\d{4})-(\d{2})-(\d{2})\b/.exec(s);
    if(m){ const t=Date.UTC(+m[1],+m[2]-1,+m[3]); if(!isNaN(t)) return {min:t,max:t}; }
    m=/\b(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})\b/.exec(s);
    if(m){ const a=+m[1], b=+m[2], y=+m[3], reads=[];
      if(b>=1&&b<=12&&a>=1&&a<=31) reads.push(Date.UTC(y,b-1,a));
      if(a>=1&&a<=12&&b>=1&&b<=31) reads.push(Date.UTC(y,a-1,b));
      if(reads.length) return {min:Math.min(...reads),max:Math.max(...reads)}; }
  }
  return null;
}
// "femoral component" also names a HIP part; a knee ceiling must never be
// applied to it.
const HIP_WORDS=/\b(hip|acetabul\w*|bipolar|unipolar|thr|stem|neck|head)\b/;
function analyse(data,now){
  let unreadable=0;
  const amt=v=>{ const p=parseAmount(v); if(p.bad) unreadable++; return p.n; };
  const lines=(data.line_items||[]).map(l=>{
    // Only the line total (and the printed gross) feed a sum, so only those count
    // as "amounts that could not be read". Quantity and rate text such as
    // "2 Nos" or "500/-" is read if it can be and ignored if it cannot.
    let q=parseAmount(l.quantity).n; const tot=amt(l.total), rate=parseAmount(l.rate).n;
    if(tot!=null&&tot<0&&q!=null&&q>0) q=-Math.abs(q);
    return {item:String(l.item||''),unit:l.unit??null,quantity:q,rate,total:tot,section:l.section||l.category||null};
  });
  const H=data.header||{};
  // A credit line (a refund, return or discount shown as a negative amount) is
  // not a charge, and a charge cancelled by an equal credit line is not one
  // either: neither is matched against the lists, so a refunded item can never
  // appear in the letter as something to explain.
  const baseName=s=>String(s).toLowerCase().replace(/\b(refund(ed)?|return(ed)?|reversal|reversed|credit(ed)?|cancel(l?ed)?)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim();
  const credit=new Set(), cancelled=new Set();
  lines.forEach((l,i)=>{ if(l.total==null||l.total>=0) return; credit.add(i);
    const j=lines.findIndex((p,pj)=>p.total>0&&!cancelled.has(pj)&&Math.abs(p.total+l.total)<0.005&&baseName(p.item)===baseName(l.item));
    if(j>=0) cancelled.add(j); });
  // IRDAI Lists II-IV ("should already be in another charge") are matched
  // before List I, and a line caught here is not also offered to the List I
  // loop below — the two describe different problems with the same line, and
  // showing it under both would look like a double count.
  const subsumed=[]; const subsumedIdx=new Set();
  lines.forEach((l,i)=>{ if(credit.has(i)||cancelled.has(i)) return; const m=bestMatchIn(l.item,SUBSUMED); if(!m) return;
    subsumedIdx.add(i); subsumed.push({...l,matched:m.e.item,list:m.e.list}); });
  const subsumedSum=money(subsumed.reduce((s,r)=>s+(r.total||0),0));
  const exact=[],review=[];
  lines.forEach((l,i)=>{ if(credit.has(i)||cancelled.has(i)||subsumedIdx.has(i)) return; const m=bestMatch(l.item); if(!m) return;
    (m.e.tier==='exact'?exact:review).push({...l,matched:m.e.item,basis:m.e.basis||'list_i'}); });
  const sum=a=>money(a.reduce((s,r)=>s+(r.total||0),0));
  const lineSum=sum(lines);
  let recon=null; const g=amt(H.gross_amount);
  const reconCompared=g!=null;   // no printed total read => "not compared", never "clear"
  if(g!=null){ const d=money(g-lineSum); if(Math.abs(d)>=1) recon={diff:d,gross:money(g),lineSum}; }
  // Repeated charges: same item text and same amount. Ignored: blank items and
  // zero/missing amounts (a repeated 0.00 row is layout, not a double charge).
  // A charge that was reversed (a matching negative line) is netted out — that
  // is a correction, not a duplicate. Recurring services (room rent, daily
  // visits) can legitimately repeat, so the wording asks the user to check.
  const keyOf=(item,amount)=>item.trim().toLowerCase()+'|'+amount.toFixed(2);
  const pos={},neg={};
  lines.forEach(l=>{ if(!l.item.trim()||l.total==null||l.total===0) return;
    if(l.total>0) pos[keyOf(l.item,l.total)]=(pos[keyOf(l.item,l.total)]||0)+1;
    else neg[keyOf(l.item,-l.total)]=(neg[keyOf(l.item,-l.total)]||0)+1; });
  const dups=[];
  lines.forEach(l=>{ if(!l.item.trim()||l.total==null||l.total<=0) return;
    const k=keyOf(l.item,l.total), net=(pos[k]||0)-(neg[k]||0);
    if(net>1&&!dups.find(d=>d.k===k)) dups.push({k,item:l.item,amount:l.total,n:net}); });
  // Lines that are identical apart from a trailing reference number (many
  // hospital systems append a per-line code: "CBC COMPLETE BLOOD COUNT 10449")
  // at the same amount. The exact match above cannot see these, so a real
  // repeat with two different codes went unflagged (R11). Kept SEPARATE from
  // `dups` and worded as "look alike", never "appears twice": a different code
  // may well mean a different, legitimate service. Only a 3+ digit trailing
  // number is treated as a code, and anything else in the text (a doctor's
  // name in brackets, a size) must match exactly.
  const coreOf=s=>s.trim().toLowerCase().replace(/\s+\d{3,}$/,'').trim();
  const simGroups=new Map();
  Object.keys(pos).forEach(k=>{ const net=pos[k]-(neg[k]||0); if(net<1) return;
    const bar=k.lastIndexOf('|'), item=k.slice(0,bar), amt=k.slice(bar+1), core=coreOf(item);
    const gk=core+'|'+amt, g=simGroups.get(gk)||{core,amount:+amt,keys:[],n:0};
    g.keys.push(item); g.n+=net; simGroups.set(gk,g); });
  const similarDups=[];
  simGroups.forEach(g=>{ if(g.keys.length<2) return;
    const shown=g.keys.map(k=>(lines.find(l=>l.item.trim().toLowerCase()===k)||{item:k}).item.trim());
    similarDups.push({items:shown,amount:g.amount,n:g.n}); });
  const missing=[],malformed=[];
  // A placeholder is not a value. "Provisional Bill" is truthy and non-blank,
  // so the old isBlank-only test let it through as "present" — this bill is
  // never the final numbered record IS 19493 expects, and that's a real
  // finding, not a reading error.
  const PLACEHOLDER_RE=/^(provisional|draft|temp(orary)?|sample|test|not\s*final)\b/i;
  // Signature fields come back as booleans, not strings — the generic blank
  // test below would read `false` as a non-empty value and call it present.
  const BOOL_FIELDS=new Set(["patient_signature","authorised_signature"]);
  // A blank field can mean two different things, and only one is a finding.
  // "missing" = the hospital didn't print it. "redacted" = we blacked it out
  // ourselves before analysis (set on data._redacted_header_fields, as the
  // real test bill is) — nothing can be concluded from that, and it must
  // never be counted as the hospital's failure. Conditional fields (per
  // IS19493_HEADER's third column) never count as missing either, matching
  // 03_code/completeness.js.
  const redactedSet=new Set(data._redacted_header_fields||[]);
  const redacted=[];
  for(const [k,label,sev] of IS19493_HEADER){
    const v=H[k];
    const blank=BOOL_FIELDS.has(k) ? v!==true
      : (v==null||String(v).trim()===''||/^(n\/?a|nil|none|-|--)$/i.test(String(v).trim()));
    if(blank){
      if(redactedSet.has(k)){ if(sev==='mandatory') redacted.push(label); continue; }   // we removed it — not assessable, not the hospital's fault
      if(sev==='mandatory') missing.push(label);
    }
    else if(k==='bill_number'&&PLACEHOLDER_RE.test(String(v).trim())) missing.push(`${label} (reads "${String(v).trim()}", not a final bill number)`);
    else if(k==='hospital_gstin'&&!GSTIN_RE.test(String(v).replace(/\s/g,''))) malformed.push(label);
  }
  const noUnit = lines.length>0 && lines.every(l=>l.unit==null);
  const nppa=[], nppaGst=[]; let nppaStale=false, nppaCompared=0, nppaSkipped=0, nppaDated=0;
  const clock=(now instanceof Date?now:new Date()).getTime();
  const bd=billDateRange(H);
  // "Past its validity" is judged at the BILL's date when it can be read (a bill from
  // inside the validity period is not stale just because today is later); if the date
  // is missing or ambiguous across the boundary, today's date is used.
  const isStale=validTo=>bd?(bd.min>validTo?true:(bd.max<=validTo?false:clock>validTo)):clock>validTo;
  // A ceiling is for ONE part. A line that is a set, kit or package, or names
  // two parts (femoral + tibial ...), is not comparable and is never flagged.
  const SET_WORDS=/\b(set|kit|package|pkg|combo)\b/;
  const FAMILIES=[/femoral/,/tibial/,/patell/,/insert|articulating/];
  // Punctuation is a space here, as in every other matcher (_normTxt): the
  // standard spelling "DRUG-ELUTING STENT" used to miss the "drug eluting
  // stent" keyword entirely, and the report then said no stent was on the
  // bill at all (R11).
  const nppaHit=(c,t)=>{ const k=c.kw.find(k=>t.includes(k)); if(k) return k;
    const r=c.req&&c.req.find(ws=>ws.every(w=>_hasWord(t,w))); return r?r.join(' '):null; };
  for(let i=0;i<lines.length;i++){ if(credit.has(i)||cancelled.has(i)) continue; const l=lines[i], t=_normTxt(l.item);
    for(const c of NPPA){ const hit=nppaHit(c,t); if(hit){
      const knee=c.item.startsWith('Knee');
      if(knee&&HIP_WORDS.test(t)) break;
      const stent=c.item.startsWith('Coronary stent');
      if(stent&&bd&&bd.min<NPPA_STENT_FROM){ nppaDated++; break; }
      // Two parts = a part word from a family the matched ceiling doesn't
      // cover. Counting family words alone skipped NPPA's own "Tibial tray +
      // insert" and "tibial insert" ceilings, whose official names span two
      // families, so those rows could never be compared (R11). Stent lines
      // keep the original count, since no knee family belongs to a stent.
      const own=FAMILIES.filter(f=>f.test(c.item.toLowerCase())||f.test(hit));
      const multiPart=knee?FAMILIES.some(f=>!own.includes(f)&&f.test(t)):FAMILIES.filter(f=>f.test(t)).length>1;
      if(SET_WORDS.test(t)||multiPart){ nppaSkipped++; break; }
      // The price per unit. A rate of 0 (the extraction template's placeholder) is
      // "no rate". When both a rate and total/quantity exist the LOWER one is used,
      // so a line total copied into the rate column cannot create a flag.
      const rate=l.rate>0?+l.rate:null, per=(l.total!=null&&l.total>0&&l.quantity)?(+l.total/Math.abs(l.quantity)):null;
      const price=(rate!=null&&per!=null)?Math.min(rate,per):(rate!=null?rate:per);
      if(price!=null) nppaCompared++;
      // At or below the ceiling: never flagged.
      if(price!=null&&price>c.ceiling){
        const stale=isStale(knee?NPPA_KNEE_VALID_TO:NPPA_STENT_REVIEW_FROM-1000);
        const row={item:l.item,price:money(price),ceiling:c.ceiling,ref:c.item,gst:c.gst,grade:c.grade||'verify',stale};
        if(price>c.ceiling*NPPA_GST_FACTOR){ nppa.push(row); if(stale) nppaStale=true; }
        else nppaGst.push(row);
      }
      break;
    }}
  }
  // Lines with letters but no English letters (Hindi, Marathi ...) cannot be matched
  // against the English lists; say so instead of implying they were checked.
  const nonLatin=lines.filter(l=>/\p{L}/u.test(l.item)&&!/[A-Za-z]/.test(l.item)).length;
  // Structural hedges only (no invented threshold): one page uploaded, or a
  // page rejected as not-a-bill. Set by the upload flow on the merged object.
  const partial=data._pageCount===1||(data._rejected||0)>0;
  const subtotals = data.printed_subtotals && Object.keys(data.printed_subtotals).length ? data.printed_subtotals : null;
  return {lines,header:H,exact,review,exactSum:sum(exact),reviewSum:sum(review),lineSum,recon,dups,similarDups,missing,malformed,redacted,noUnit,nppa,nppaGst,nppaStale,nppaCompared,nppaSkipped,nppaDated,nonLatin,subtotals,unreadable,reconCompared,partial,subsumed,subsumedSum,rejected:data._rejected||0,pageCount:data._pageCount||null};
}

module.exports = { NON_PAYABLE, SUBSUMED, NPPA, OMBUDSMAN, OMBUDSMAN_READ_ON, INDIA_STATES, ombudsmanFor, IS19493_HEADER, GSTIN_RE, money, bestMatch, bestMatchIn, parseAmount, billDateRange, analyse };
