/* AUTO-GENERATED by lib/build_checks.js from the "reader" region of 06_app/index.html - do not edit.
 * Re-run `node lib/build_checks.js` after changing that region. `--check` fails if stale. */
/* reader */
// Everything between the "reader" markers is DOM-free on purpose:
// lib/build_checks.js copies it into lib/reader.js so the reading logic is
// tested in Node against a mock fetch (lib/test_reader.js). Keep it free of any
// reference to the page or browser storage — the build fails if one is added.
const PHOTO_MIME=/^image\/(jpeg|jpg|png|webp|heic|heif)$/i;
const EXT_MIME={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',heic:'image/heic',heif:'image/heif'};
// Some phones report an empty type for a real photo; only then (or the generic
// octet-stream type) is the file extension used. A stated type such as
// application/pdf is never overridden by the name.
function fileMime(f){
  const t=(f&&f.type)||'';
  if(t&&t!=='application/octet-stream') return PHOTO_MIME.test(t)?t:null;
  const m=/\.([a-z0-9]+)$/i.exec((f&&f.name)||'');
  return (m&&EXT_MIME[m[1].toLowerCase()])||null;
}
const isPhoto=f=>!!fileMime(f);
// The same photo picked twice has the same name, size and modified time.
const fileKey=f=>[f.name||'',f.size||0,f.lastModified||0].join('|');
function mkErr(kind,status){ const e=new Error(kind); e.kind=kind; if(status) e.status=status; return e; }
// Turn an HTTP status into a stable "kind"; the screen turns the kind into a
// plain sentence in the user's language. code = the proxy's error code, if any.
function kindForStatus(status,direct,code){
  if(status===429) return direct?'quota':'busy';
  if(direct){ if(status===400||status===401||status===403) return 'key'; return status>=500?'server':'unreadable'; }
  if(status===413) return 'toolarge';
  if(status===415) return 'unsupported';
  if(status===504) return 'timeout';
  if(status===502&&(code==='empty'||code==='unreadable')) return 'unreadable';
  return 'server';
}
// One page in, one structured object out; a failure is an Error with .kind.
// o: {key,useProxy,proxyState,fetchFn,toB64,stripFence,directRequest,signal,timeoutMs,isOffline}
async function readOnePage(file,o){
  const mime=fileMime(file);
  const b64=await o.toB64(file);
  const ac=new AbortController(); let timedOut=false;
  const onAbort=()=>ac.abort();
  if(o.signal){ if(o.signal.aborted) throw mkErr('cancelled'); o.signal.addEventListener('abort',onAbort); }
  const t=setTimeout(()=>{ timedOut=true; ac.abort(); },o.timeoutMs||100000);
  try{
    let txt;
    // If the free service says it is busy (429), the user can paste their own
    // free Gemini key and continue — then this page goes direct to Google.
    if(o.useProxy && !(o.proxyState.busy && o.key)){
      const res=await o.fetchFn('api/read-bill',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mime_type:mime,data:b64}),signal:ac.signal});
      txt=await res.text();
      if(!res.ok){ let code=''; try{ code=JSON.parse(txt).error||''; }catch(e){}
        const kind=kindForStatus(res.status,false,code); if(kind==='busy') o.proxyState.busy=true; throw mkErr(kind,res.status); }
    } else {
      const dr=o.directRequest(o.key,mime,b64);
      const res=await o.fetchFn(dr.url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(dr.body),signal:ac.signal});
      if(!res.ok) throw mkErr(kindForStatus(res.status,true),res.status);
      const j=await res.json(); txt=j&&j.candidates&&j.candidates[0]&&j.candidates[0].content&&j.candidates[0].content.parts&&j.candidates[0].content.parts[0]&&j.candidates[0].content.parts[0].text||'';
    }
    let page; try{ page=JSON.parse(o.stripFence(txt)); }catch(e){ throw mkErr('unreadable'); }
    if(!page||typeof page!=='object'||Array.isArray(page)) throw mkErr('unreadable');
    return page;
  }catch(e){
    if(e&&e.kind) throw e;
    if(o.signal&&o.signal.aborted) throw mkErr('cancelled');
    if(timedOut) throw mkErr('timeout');
    throw mkErr('offline');   // fetch itself failed: no signal, DNS, dropped connection
  }finally{ clearTimeout(t); if(o.signal) o.signal.removeEventListener('abort',onAbort); }
}
// Reads every page in order and returns one result per file:
//   {status:'ok',page,cached?} | {status:'dup',of} | {status:'failed',kind} | {status:'skipped',kind}
// Pages already read (o.cache, keyed by fileKey) are not sent again, an
// identical file is read once, and a failure never discards the pages that
// worked. Nothing here retries by itself: every call is one the user asked for.
async function readPages(files,o){
  const results=new Array(files.length).fill(null), seen=new Map(); let streak=0;
  for(let i=0;i<files.length;i++){
    const k=fileKey(files[i]);
    if(seen.has(k)){ results[i]={status:'dup',of:seen.get(k)}; continue; }
    seen.set(k,i);
    if(o.cache&&o.cache.has(k)){ results[i]={status:'ok',page:o.cache.get(k),cached:true}; continue; }
    if(o.signal&&o.signal.aborted){ results[i]={status:'skipped',kind:'cancelled'}; continue; }
    if(o.onProgress) o.onProgress(i,files.length);
    try{ const page=await readOnePage(files[i],o); if(o.cache) o.cache.set(k,page); results[i]={status:'ok',page}; streak=0; }
    catch(e){
      const kind=(e&&e.kind)||'server'; results[i]={status:'failed',kind};
      streak=(kind==='timeout'||kind==='server')?streak+1:0;
      // Stop early when going on cannot help: cancelled, offline, busy, a bad key,
      // or two slow/failed pages in a row (do not make someone wait 100 s per page).
      if(kind==='cancelled'||kind==='offline'||kind==='busy'||kind==='key'||kind==='quota'||streak>=2){
        for(let j=i+1;j<files.length;j++) if(!results[j]) results[j]={status:'skipped',kind};
        break;
      }
    }
  }
  for(let i=0;i<results.length;i++) if(!results[i]) results[i]={status:'skipped',kind:'server'};
  return results;
}

module.exports = { PHOTO_MIME, fileMime, isPhoto, fileKey, mkErr, kindForStatus, readOnePage, readPages };
