/* Keeps the two reference copies of the IRDAI table in step with the app.
 *
 * The app (06_app/index.html, NON_PAYABLE) is the single source of truth for
 * what is matched. This script regenerates
 *   - 02_reference_data/irdai_non_payables.csv
 *   - 03_code/lookup_table_for_prompt.txt
 * from it, so the three copies cannot disagree (they had drifted: 17 rows were
 * "exact" in the files but "review" in the app).
 *
 *   node lib/sync_reference.js          rewrite both files
 *   node lib/sync_reference.js --check  exit 1 if either file is out of step
 *
 * Note: 02_reference_data/build_irdai.py is the original one-off builder of the
 * CSV and no longer produces the current table; do not run it over these files.
 */
const fs = require('fs');
const path = require('path');
const { NON_PAYABLE } = require('./checks.js');

const REPO = path.join(__dirname, '..', '..');
const CSV = path.join(REPO, '02_reference_data', 'irdai_non_payables.csv');
const TXT = path.join(REPO, '03_code', 'lookup_table_for_prompt.txt');
const SOURCE = 'IRDAI List of Non-Medical / Non-Payable Items (as circulated by insurers)';
const DATE = '2017-01-01';
const key = s => String(s).toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

// Category for rows added after the CSV was first built (existing rows keep theirs).
const NEW_CATEGORY = {
  'television charges': 'guest', 'mortuary charges': 'administrative', 'extra diet of patient': 'guest',
  'private nurses charges special nursing charges': 'ward', 'abdominal binder': 'equipment', 'lumbo sacral belt': 'equipment',
  'pelvic traction belt': 'equipment', 'nimbus bed water bed air bed charges': 'equipment', 'spirometer': 'equipment',
  'sugar free tablets': 'consumable', 'vasofix safety': 'consumable', 'leggings': 'equipment', 'pan can': 'equipment',
  'blood grouping and cross matching of donors samples': 'administrative', 'food charges only non patient food is excluded': 'guest',
  'ambulance excluded unless your policy covers it': 'ward',
};

function parseCsv(text) {
  const rows = []; let row = [], cur = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (q) { if (ch === '"') { if (text[i + 1] === '"') { cur += '"'; i++; } else q = false; } else cur += ch; }
    else if (ch === '"') q = true;
    else if (ch === ',') { row.push(cur); cur = ''; }
    else if (ch === '\n') { row.push(cur); rows.push(row); row = []; cur = ''; }
    else if (ch !== '\r') cur += ch;
  }
  if (cur || row.length) { row.push(cur); rows.push(row); }
  return rows.filter(r => r.length > 1);
}
const csvField = s => /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;

function build() {
  const existing = new Map();
  if (fs.existsSync(CSV)) {
    const rows = parseCsv(fs.readFileSync(CSV, 'utf8')); const head = rows[0];
    for (const r of rows.slice(1)) { const o = {}; head.forEach((h, i) => o[h] = r[i]); existing.set(key(o.item), o); }
  }
  const meta = NON_PAYABLE.map(r => {
    const e = existing.get(key(r.item));
    const category = (e && e.category) || NEW_CATEGORY[key(r.item)];
    if (!category) throw new Error('no category for new row: ' + r.item + ' (add it to NEW_CATEGORY in sync_reference.js)');
    return { ...r, category, source: (e && e.source_document) || SOURCE, date: (e && e.effective_date) || DATE };
  });
  const exact = meta.filter(r => r.tier === 'exact').length, review = meta.length - exact;
  const csv = ['item,category,match_keywords,confidence,source_document,effective_date,basis,not_keywords']
    .concat(meta.map(r => [r.item, r.category, r.keywords, r.tier, r.source, r.date, r.basis || '', r.not || ''].map(csvField).join(','))).join('\n') + '\n';
  const txt = [
    `// Generated by 06_app/lib/sync_reference.js from 06_app/index.html (${meta.length} rows: ${exact} exact, ${review} review). Do not edit by hand.`,
    '// exact  = named in the published IRDAI non-payable list; safe to flag.',
    '// review = commonly deducted but NOT named in the list; needs a human. Never merge the two.',
  ].concat(meta.map(r => `  { tier: "${r.tier}", item: ${JSON.stringify(r.item)}, category: "${r.category}", keywords: ${JSON.stringify(r.keywords)}` +
    (r.basis ? `, basis: "${r.basis}"` : '') + (r.not ? `, not: ${JSON.stringify(r.not)}` : '') + ' },')).join('\r\n') + '\r\n';
  return { csv, txt };
}

if (require.main === module) {
  const out = build();
  const norm = f => fs.existsSync(f) ? fs.readFileSync(f, 'utf8').replace(/\r\n/g, '\n') : '';
  if (process.argv.includes('--check')) {
    const bad = [];
    if (norm(CSV) !== out.csv.replace(/\r\n/g, '\n')) bad.push('02_reference_data/irdai_non_payables.csv');
    if (norm(TXT) !== out.txt.replace(/\r\n/g, '\n')) bad.push('03_code/lookup_table_for_prompt.txt');
    if (bad.length) { console.error('STALE reference copies: ' + bad.join(', ') + ' - run: node lib/sync_reference.js'); process.exit(1); }
    console.log('reference CSV and prompt table match the app (' + NON_PAYABLE.length + ' rows)');
  } else {
    fs.writeFileSync(CSV, out.csv); fs.writeFileSync(TXT, out.txt);
    console.log('wrote irdai_non_payables.csv and lookup_table_for_prompt.txt (' + NON_PAYABLE.length + ' rows)');
  }
}
module.exports = { build };
